export default function Terms() {
  return (
    <div className="min-h-screen pt-24 pb-16 px-4">
      <div className="max-w-4xl mx-auto">
        <h1 className="font-heading text-4xl font-bold text-velvet-gold mb-8">Terms of Service</h1>
        <p className="text-gray-400 text-sm mb-8">Last updated: May 2026</p>

        <div className="space-y-8 text-gray-300 text-sm leading-relaxed">
          <section>
            <h2 className="font-heading text-xl font-bold text-white mb-3">1. Eligibility</h2>
            <p>
              You must be at least 18 years of age (or the age of majority in your jurisdiction) to access 
              or use The Velvet Suite. By using our service, you represent and warrant that you meet this 
              age requirement. We reserve the right to terminate accounts of users who do not meet this 
              eligibility requirement.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-bold text-white mb-3">2. Service Description</h2>
            <p>
              The Velvet Suite provides AI-powered companion chat services for adult users. Our AI companions 
              are artificial intelligence programs designed for entertainment and companionship purposes. They 
              are not real people and do not constitute real relationships. All conversations are generated by 
              AI and should be understood as fictional interactions.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-bold text-white mb-3">3. Subscriptions & Payments</h2>
            <p>
              Subscription plans are billed on a recurring basis (monthly or annually) as selected at the time 
              of purchase. Prices are subject to change with notice. You may cancel your subscription at any time, 
              and cancellation will take effect at the end of the current billing period. No refunds will be 
              provided for partial billing periods. All payments are processed securely through our payment provider.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-bold text-white mb-3">4. Content & Acceptable Use</h2>
            <p>
              While The Velvet Suite permits adult content in conversations, users must not use the service to:
            </p>
            <ul className="list-disc list-inside mt-2 space-y-1 text-gray-400">
              <li>Generate content involving minors in any sexual context</li>
              <li>Plan or promote illegal activities</li>
              <li>Harass, threaten, or harm real individuals</li>
              <li>Distribute generated content in violation of applicable laws</li>
              <li>Attempt to reverse-engineer or exploit the AI systems</li>
              <li>Use the service for any commercial purpose without authorization</li>
            </ul>
          </section>

          <section>
            <h2 className="font-heading text-xl font-bold text-white mb-3">5. Intellectual Property</h2>
            <p>
              All content, branding, and technology comprising The Velvet Suite are owned by Shocker Studios. 
              Users retain no ownership rights over AI-generated content. You may not reproduce, distribute, 
              or create derivative works from our service without express written permission.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-bold text-white mb-3">6. Limitation of Liability</h2>
            <p>
              The Velvet Suite is provided "as is" without warranties of any kind. Shocker Studios shall not 
              be liable for any indirect, incidental, special, consequential, or punitive damages arising from 
              your use of the service. Our total liability shall not exceed the amount paid by you in the 
              preceding 12 months. AI-generated content may not always be accurate, appropriate, or aligned 
              with your expectations.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-bold text-white mb-3">7. Termination</h2>
            <p>
              We reserve the right to suspend or terminate your access to The Velvet Suite at any time, 
              with or without cause, and with or without notice. Upon termination, your right to use the 
              service will immediately cease, and we may delete your data in accordance with our Privacy Policy.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-bold text-white mb-3">8. Changes to Terms</h2>
            <p>
              We may update these Terms of Service at any time. Continued use of the service after changes 
              constitutes acceptance of the new terms. We will make reasonable efforts to notify users of 
              significant changes.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-bold text-white mb-3">9. Contact</h2>
            <p>
              For questions about these Terms of Service, contact us at:{' '}
              <a href="mailto:support@shockersvelvetsuite.shop" className="text-velvet-gold hover:underline">
                support@shockersvelvetsuite.shop
              </a>
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
